# Generated by Django 6.1 on 2026-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="product",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
