# Generated by Django 6.1 on 2026-08-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
